{{- if and .Values.postal.web.ingress.tlsEnabled .Values.postal.web.ingress.certManager.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "postal.fullname" . }}-web
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- range $k, $v := .Values.postal.web.ingress.certManager.labels }}
    {{$k}}: {{$v | quote}}
    {{- end }}
spec:
  commonName: {{ required "postal.web.ingress.hostname is required" .Values.postal.web.ingress.hostname }}
  dnsNames:
  - {{ required "postal.web.ingress.hostname is required" .Values.postal.web.ingress.hostname }}
  issuerRef:
    name: {{ required "postal.web.ingress.certManager.issuerName is required" .Values.postal.web.ingress.certManager.issuerName }}
    kind: {{ required "postal.web.ingress.certManager.issuerKind is required" .Values.postal.web.ingress.certManager.issuerKind }}
  secretName: {{ template "postal.fullname" . }}-web-tls
{{- end }}
